### ISSUE TITLE
Class 'Fortress\\MessageStream' not found

### ISSUE THREAD

**Issue by FniCoconut** [userfrosting/fortress#14]
Hello, at first sorry for my english.

I've got a problem with my page since I've updated fortress with composer.
I'm navigating throught UserFrosting's code and doing the tutorials.

When I've finished the lesson 2 the server returns me HTTP 404 and I thought that I haven't got updated something. I've visited this instalation guide and done

`composer require alexweissman/fortress` 

and after this my error.log returns:

> [Mon Sep 19 20:06:47.280566 2016] [:error] [pid 7378] [client ::1:43436] PHP Fatal error:  Uncaught Error: Class 'Fortress\\MessageStream' not found in /var/www/html/userfrosting/userfrosting/models/UserFrosting.php:49\nStack trace:\n#0 /var/www/html/userfrosting/userfrosting/models/UserFrosting.php(27): UserFrosting\\UserFrosting->setupServices('en_US')\n#1 /var/www/html/userfrosting/userfrosting/initialize.php(185): UserFrosting\\UserFrosting->setupGuestEnvironment()\n#2 /var/www/html/userfrosting/public/index.php(11): require_once('/var/www/html/u...')\n#3 {main}\n  thrown in /var/www/html/userfrosting/userfrosting/models/UserFrosting.php on line 49, referer: http://localhost/userfrosting/

How can I solve without reinstall or destroy all what I've done before?

Thanks!

**Comment by alexweissman** [comment]
Hi @FniCoconut,

Thanks for checking out UserFrosting!  The issues tracker is only for feature requests and bug reports.  Please ask your question in [chat](https://chat.userfrosting.com) instead.
