### ISSUE TITLE
Implement some unit tests

### ISSUE THREAD

**Issue by alexweissman** [userfrosting/fortress#19]
We desperately need some unit tests for this module.  Does phpunit support a way to mock JSON objects?

**Comment by lcharette** [comment]
Yes it does: https://phpunit.de/manual/current/en/appendixes.assertions.html#appendixes.assertions.assertJsonStringEqualsJsonString

**Comment by alexweissman** [comment]
There's gonna be a lot of test cases to write 😓

**Comment by alexweissman** [comment]
Alright, the deed is done.  I'm testing the output of `JqueryValidationAdapter` directly as a PHP array, because I am assuming that PHP's `json_encode` function works properly.  In fact, UserFrosting doesn't even bother converting to JSON in the controller anyway - we pretty much always handle that in Twig templates.

I'm not bothering to write tests for `FormValidationAdapter`, because I doubt anyone is actually using the FormValidation plugin anyway.
