### ISSUE TITLE
Fortress Message Translator : Append to existing Locale array

### ISSUE THREAD

**Issue by ssnukala** [userfrosting/fortress#2]
Currently the Message translator 

```
    $this->translator->setTranslationTable($this->config("locales.path") . "/" . $locale . ".php");
```

only reads one file and the methods in the Fotress/MessageTranslator Class do not have a way to append to the messages that are already loaded.

Would like to have a method to append to existing messages, so that the UserFrosting plugins can add to the messages and use locale files in plugin directories instead of writing to the locale files under the userfrosting/locale directory. 

Thinking about something like

```
public function appendTranslationTable($path){
    $append_table = include($path);
    $this->_translation_table = array_merge($append_table,$this->_translation_table);
}

public function appendTranslationTable($locale_array){
    $this->_translation_table = array_merge($locale_array,$this->_translation_table);
}
```

we could also make this function take a PHP array as input

**Comment by alexweissman** [comment]
Yes, I agree.  Maybe we can come up with a system where UF auto-loads and appends the translation files for each plugin, so that the plugins don't have to explicitly call `appendTranslationTable`.

Also, we will need some kind of scoping system, so that message tokens with the same name in different plugins don't collide with one another.

**Comment by ssnukala** [comment]
we can change this to add one more parameter ($SCOPE) and use this to pick the message within the scope. 
    public function translate($scope, $message_id, $placeholders = []){

And change all the calling functions to implement $scope parameter.

For autoload
1. we can just autoload all plugin/locale files based on the language settings by default
2. OR - let he plugin explicitly register Locale flies like we are doing with 
$app->schema->registerJS("
we could potentially have 
$app->schema->registerLocale("scope",file path);

**Comment by ssnukala** [comment]
check this out

https://github.com/ssnukala/fortress/blob/master/fortress/MessageTranslator.php#L31-L62

**Comment by alexweissman** [comment]
All of these issues have been solved with the Sprinkle system, file streams, and the new [i18n module](https://github.com/userfrosting/i18n) in UF4.  You can set multiple locale paths to search using `MessageTranslator::setPaths`, and then load a list of language files (for UF to fall back on if a key doesn't exist) using `MessageTranslator::loadLocaleFiles`.

In fact, this is how it is done in the current `translator` service: https://github.com/userfrosting/UserFrosting/blob/189c984f973a8fe569d7d6cf43f3fbdcf8198253/app/sprinkles/core/src/ServicesProvider/CoreServicesProvider.php#L558-L589

You can even dynamically load translation mappings from a file or array using `mergeLocaleFile` and `mergeItems`, respectively.
